name: Remote Dispatch Action Initiator

on:
  push:
    branches: [master, 'v[0-9].[0-9].[0-9]']
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating repository event
       
        run: |
          curl -X POST https://api.github.com/repos/andreic-ensemble/codetest/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
