name: Remote Deploy Action Initiator

on:
  push:
    branches: [master, 'v[0-9].[0-9].[0-9]']
  repository_dispatch:

jobs:
  initiate_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch initiating deployment
       
        run: |
          curl -X POST https://api.github.com/repos/andreic-ensemble/codetest/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u  ${{ secrets.USER_NAME }}:${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "initiate_deploy", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
